### ISSUE TITLE
StarRocksTableSink should support  the configuration of `sink.parallelism`

### ISSUE THREAD

**Issue by shouweikun** [StarRocks/flink-connector-starrocks#20]
Since Flink SQL has already supported `sink.parallelism` in its planner,  we should support `sink.parallelism` in StarrocksTableSink too. 

As I've mentioned above, Flink has support it in planner, so it is just a trival change to enable `sink.parallelism`. 
If no one is working on it, I’m willing to doing that😊.

FYI : https://issues.apache.org/jira/browse/FLINK-19727

**Comment by hffariel** [comment]
Thanks for the feedback and looking forward to your PR.
