### ISSUE TITLE
去除load-url参数功能设计

### ISSUE THREAD

**Issue by liukunyuan** [StarRocks/flink-connector-starrocks#27]
用户只需要提供jdbc-url，而不用提供load-url参数。我已经实现了，可以提pr贡献吗

**Comment by hffariel** [comment]
当然可以啊

**Comment by hffariel** [comment]
但是顺便提醒下如果是普通用户权限的话是不可以执行 show frontends 的~

**Comment by liukunyuan** [comment]
目前的思路是通过jdbc连接fe，然后执行SHOW PROC '/backends'命令。得到be列表。思路和flink doris connector差不多。不过flink doris是通过http去得到be列表的，可能存在不兼容问题。而通过jdbc得到be列表，兼容性比较好。

补充：同步数据的用户，应该是需要给开SHOW PROC '/backends'权限的。如果权限不够，才从load-url中获取，给用户多一个选择。这样非常简洁

**Comment by hffariel** [comment]
我是这样看的：
1. 从已知的企业用户来看，很多都不会给这么高的权限，可能只给某些表的导入权限。
2. 应该是通过jdbc取frontends，所有的请求都交由frontends来处理，否则需要把fe的stream load 均衡路由逻辑拿过来。
3. 如果是直接取frontends的列表的话，会面临一个问题就是有些用户可能是从外网访问的，但是他们从starrocks拿到的be地址是内网地址导致无法请求。（这种情况需要直接访问be，但是会出现均衡问题，所以可能要frontends和backends全部取出来尝试链接校验一遍才可以。）
