### ISSUE TITLE
use canal-json can not insert starrocks

### ISSUE THREAD

**Issue by lq351334131** [StarRocks/flink-connector-starrocks#31]
tableEnv.executeSql("CREATE TABLE tb_order(\n" +
                "    id INT,\n" +
                "    order_num STRING,\n" +
                "    counter_code STRING,\n" +
                "    price INT,\n" +
                "    status INT \n" +
                "  )  WITH (\n" +
                "'connector' = 'kafka',\n" +
                "'topic' = 'tb_order',\n" +
                "'scan.startup.mode' = 'latest-offset',\n" +
                "'properties.bootstrap.servers' = 'hadoop001.test.com:9092,hadoop002.test.com:9092,hadoop003.test.com:9092 ', \n" +
                "'format' = 'canal-json', \n" +
                "'properties.group.id' = 'liqitest',\n" +
                // "'json.fail-on-missing-field' = 'false', \n" +
                "'canal-json.ignore-parse-errors' = 'true' \n "+
                ")");

        tableEnv.executeSql(
                "CREATE TABLE mytest03 (" +
                        "id INT," +
                        "order_num STRING," +
                        "counter_code STRING," +
                        "price INT ," +
                        "status INT " +
                        //" PRIMARY KEY (id) NOT ENFORCED"+
                        ") WITH ( " +
                        "'connector' = 'starrocks'," +
                        "'jdbc-url'='jdbc:mysql://fat-starrocks.xxx.com:9030?characterEncoding=utf-8&useSSL=false'," +
                        "'load-url'='fat-xx.ppdapi.com:8030'," +
                        "'database-name' = 'gouya_test'," +
                        "'table-name' = 'mytest03'," +
                        "'username' = 'xxxx'," +
                        "'password' = 'xxx'," +
                        "'sink.buffer-flush.max-rows' = '65000'," +
                        "'sink.buffer-flush.max-bytes' = '67108864'," +
                        "'sink.buffer-flush.interval-ms' = '1000'," +
                        "'sink.properties.column_separator' = '\\x01'," +
                        "'sink.properties.row_delimiter' = '\\x02'," +
                        "'sink.max-retries' = '3'" +
                        ")"

        );

tableEnv.executeSql("INSERT INTO mytest03 " +
                "SELECT id, order_num,counter_code, price,status FROM tb_order ").print();
    }

can not insert into starrocks

**Comment by hffariel** [comment]
Take a look at your flink log file, there should be some more detailed info.

**Comment by hffariel** [comment]
I'm closing this issue, feel free to reopen it if it still troubles.
