### ISSUE TITLE
StarRocksStreamLoadFailedException: all partitions have no load data

### ISSUE THREAD

**Issue by liaooo** [StarRocks/flink-connector-starrocks#36]
Precondition:
1、Enable checkpoint.
2、sink.semantic = EXACTLY_ONCE

Exception:
`Caused by: com.starrocks.connector.flink.manager.StarRocksStreamLoadFailedException: Failed to flush data to StarRocks, Error response: 
{"Status":"Fail","BeginTxnTimeMs":0,"Message":"all partitions have no load data","NumberUnselectedRows":1,"CommitAndPublishTimeMs":0,"Label":"2da8b57b-bdad-4f73-b79c-b8c4664b3ad6","LoadBytes":59,"StreamLoadPutTimeMs":1,"NumberTotalRows":1,"WriteDataTimeMs":2,"TxnId":248101,"LoadTimeMs":4,"ReadDataTimeMs":0,"NumberLoadedRows":0,"NumberFilteredRows":0}`

Reason:
When checkpoint triggered, will execute the StarRocksDynamicSinkFunction#snapshotState method, Then add a Tupple2 to the checkpointedState object,  And wait for the next checkpoint to write to the StarRocks. If the buffer is empty, a StarRocksStreamLoadFailedException will be thrown. 

Suggest:
So i think the buffer should be checked if it is empty before add to checkpointedState.

**Comment by liaooo** [comment]
It's not as simple as I thought

**Comment by liaooo** [comment]
StarRocksStreamLoadVisitor#doStreamLoad(Start at line 92): 
` 
        if (loadResult.get(keyStatus).equals("Fail")) {
            // all partitions have no load data.
            // Consider compatibility, it can be controlled via StarRocksSinkOptions
            if (Objects.equals(loadResult.get("NumberTotalRows"), loadResult.get("NumberUnselectedRows"))) {
                return loadResult;
            }

            LOG.error(String.format("Stream Load response: \n%s\n", JSON.toJSONString(loadResult)));
            Map<String, String> logMap = new HashMap<>();
            if (loadResult.containsKey("ErrorURL")) {
                logMap.put("streamLoadErrorLog", getErrorLog((String) loadResult.get("ErrorURL")));
            }
            throw new StarRocksStreamLoadFailedException(String.format("Failed to flush data to StarRocks, Error " +
                "response: \n%s\n%s\n", JSON.toJSONString(loadResult), JSON.toJSONString(logMap)), loadResult);
        }
`

**Comment by hffariel** [comment]
> Precondition: 1、Enable checkpoint. 2、sink.semantic = EXACTLY_ONCE
> 
> Exception: `Caused by: com.starrocks.connector.flink.manager.StarRocksStreamLoadFailedException: Failed to flush data to StarRocks, Error response: {"Status":"Fail","BeginTxnTimeMs":0,"Message":"all partitions have no load data","NumberUnselectedRows":1,"CommitAndPublishTimeMs":0,"Label":"2da8b57b-bdad-4f73-b79c-b8c4664b3ad6","LoadBytes":59,"StreamLoadPutTimeMs":1,"NumberTotalRows":1,"WriteDataTimeMs":2,"TxnId":248101,"LoadTimeMs":4,"ReadDataTimeMs":0,"NumberLoadedRows":0,"NumberFilteredRows":0}`
> 
> Reason: When checkpoint triggered, will execute the StarRocksDynamicSinkFunction#snapshotState method, Then add a Tupple2 to the checkpointedState object, And wait for the next checkpoint to write to the StarRocks. If the buffer is empty, a StarRocksStreamLoadFailedException will be thrown.
> 
> Suggest: So i think the buffer should be checked if it is empty before add to checkpointedState.

Sorry for the late, but here is what i see:
1. The flush action was triggered under these situations: `before saving the next state during the snapshotstate`, `before the first invoking after each snapshotstate` and `close` when it comes with the `sink.semantic = EXACTLY_ONCE`.
2. The `flush` method will not put the bath-data into the queue if it's empty.

**Comment by liaooo** [comment]
[](url)

> My first comment was wrong. Actually throwing 'all partitions have no load data' is returned by StarRocks. I just hope that the Flink program doesn't fail when StarRocks returns this exception.

**Comment by hffariel** [comment]
> > My first comment was wrong. Actually throwing 'all partitions have no load data' is returned by StarRocks. I just hope that the Flink program doesn't fail when StarRocks returns this exception.

And the UPDATE_BEFORE should be ignored

**Comment by hffariel** [comment]
Feel free to reopen this issue if it still troubles.
