### ISSUE TITLE
 the data format about time type

### ISSUE THREAD

**Issue by baisui1981** [StarRocks/flink-connector-starrocks#38]
I have build a realtime synchronize channel which is from MySql table to StarRocks:
mysql table DDL:
``` sql
CREATE TABLE `base` (
  `base_id` int(11) NOT NULL,
  `start_time` datetime DEFAULT NULL,
  `update_date` date DEFAULT NULL,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`base_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```
and StarRocks table DDL
```sql
CREATE TABLE `base` (
  `base_id` int(11) NULL COMMENT "",
  `start_time` datetime NULL COMMENT "",
  `update_date` date NULL COMMENT "",
  `update_time` datetime NULL COMMENT ""
) ENGINE=OLAP
UNIQUE KEY(`base_id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`base_id`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
```
then I make some modfiies on existing rows, 
``` sql
insert into base(base_id,start_time,update_date,update_time) values(2,now(),now(),now());
```
and received row send by  Flink-CDC-MySQL-connector, example as below :
```
start_time:1639831884000,update_time:2021-12-18T04:51:24Z,base_id:3,update_date:18979
```
as a result the values of `start_time` and `update_date` is NULL:

select * from base;

+---------+------------+-------------+---------------------+
| base_id | start_time | update_date | update_time         |
+---------+------------+-------------+---------------------+
|       1 | NULL       | NULL        | 2021-12-17 09:21:20 |
+---------+------------+-------------+---------------------+

**My question is ** the data format like date or datetime must be a format '2021-12-17' or '2021-12-17 09:21:20' ?
date can not be a format as integer from 1970-01-01?

**Comment by baisui1981** [comment]
这里有两个问题
1. update_before 和 delete 类型都需要给slots set值，并请slots.length = fields.length + 1多出来的那个空位是用来指定这一行是删除还是插入更新，设置为StarRocksSinkOP.{UPSERT,DELETE}.ordinal() 
2. 第一个文件中直接取的struct的值没有被转为flink中的timestamp或date中间格式，所以date 和datetime会以整型传入，但是starrocks不支持整型load转date或datetime，所以需要在slots填值时把date, datetime, decimal 单独处理为starrocks支持的导入格式。

**Comment by jaogoy** [comment]
1970-01-01 is still a string, you can use function `str_to_date()` to convert 19700101 to datetime
