### ISSUE TITLE
Reason: there are 280 rows couldn't find a partition

### ISSUE THREAD

**Issue by itratel** [StarRocks/flink-connector-starrocks#39]
&emsp;&emsp;The flink job failed that consume data from kafka into starrocks,  since data can't found partition,  sometimes, we can't make sure that all of data both find own partition,  so I hope the flink job keep running normally, even though it occur the exception like 
` Caused by: com.starrocks.connector.flink.manager.StarRocksStreamLoadFailedException: Failed to flush data to StarRocks, Error response: `
```json
{"Status":"Fail","BeginTxnTimeMs":1,"Message":"too many filtered rows","NumberUnselectedRows":0,"CommitAndPublishTimeMs":0,"Label":"94952a3a-32ce-44bd-a9ef-97392411fa45","LoadBytes":2867274,"StreamLoadPutTimeMs":4,"NumberTotalRows":1725,"WriteDataTimeMs":2879,"TxnId":360,"LoadTimeMs":2885,"ErrorURL":"http://192.168.xx.xxx:8040/api/_load_error_log?file=__shard_34/error_log_insert_stmt_3d41ccd3-cc28-acf2-faa0-71e2679d8fb6_3d41ccd3cc28acf2_faa071e2679d8fb6","ReadDataTimeMs":15,"NumberLoadedRows":1445,"NumberFilteredRows":280}
{"streamLoadErrorLog":"Reason: there are 280 rows couldn't find a partition. src line: [[2021-12-22 15:37:00, '17de1122ff5307-04554ab9f1db16-5373e62-1395396-17de1122ff6950', 'c0cbf7ba22784439b38199145b791998', '1.0.0', 'xxxxx', 0]]; \n"}
```
Q: What should I do except keeping data find own partition?

**Comment by hffariel** [comment]
Run `show create table xxx` in starrocks to see if there exists a partition that contains the datetime `2021-12-22 15:37:00`
