### ISSUE TITLE
Current running txns on db 11027 is 100, larger than limit 100?

### ISSUE THREAD

**Issue by liaooo** [StarRocks/flink-connector-starrocks#40]
Caused by: com.starrocks.connector.flink.manager.StarRocksStreamLoadFailedException: Failed to flush data to StarRocks, Error response: 
{"Status":"Fail","BeginTxnTimeMs":0,"Message":"current running txns on db 11027 is 100, larger than limit 100","NumberUnselectedRows":0,"CommitAndPublishTimeMs":0,"Label":"a848b543-0040-4f29-839d-fb9dbb7bd61c","LoadBytes":0,"StreamLoadPutTimeMs":0,"NumberTotalRows":0,"WriteDataTimeMs":0,"TxnId":-1,"LoadTimeMs":0,"ReadDataTimeMs":0,"NumberLoadedRows":0,"NumberFilteredRows":0}

**Comment by hffariel** [comment]
Please refer to [max_running_txn_num_per_db](https://docs.starrocks.com/en-us/main/loading/Loading_intro#fe-configuration).

And try to make the `sink.buffer-flush.xxx` as large as possible to reduce the number of concurrent requests.
