### ISSUE TITLE
Is this a BUG?

### ISSUE THREAD

**Issue by liaooo** [StarRocks/flink-connector-starrocks#41]
https://github.com/StarRocks/flink-connector-starrocks/blob/e6ff56740b7a09871f0478b97a23e45658249c6b/src/main/java/com/starrocks/connector/flink/table/StarRocksDynamicSinkFunction.java#L171

The flushPreviousState method is called before that，In flushPreviousState approach through sinkManager.setBufferedBatchList() modified the buffer. 
So here sinkManager#getBufferedBatchList to buffer data is not before flushPreviousState method in the data?

**Comment by hffariel** [comment]
No, it's not. It's a little complicated here:
As you could notice, there is another [flush action](https://github.com/StarRocks/flink-connector-starrocks/blob/e6ff56740b7a09871f0478b97a23e45658249c6b/src/main/java/com/starrocks/connector/flink/table/StarRocksDynamicSinkFunction.java#L98) executed just after each `snapshotState()`. So the `checkpointedState` in the `snapshotState()` will always be empty unless `there is no data coming in during the last checkpoint cycle`(which will lead to an empty result by `sinkManager#getBufferedBatchList` no mater the `flushPreviousState()` executed or not).

**Comment by hffariel** [comment]
Closed due to no further actions.
