### ISSUE TITLE
There is a Error "parse auth info failed" in FE when using the "SinkFunction<String> sink(StarRocksSinkOptions sinkOptions)"

### ISSUE THREAD

**Issue by zhaidongbo** [StarRocks/flink-connector-starrocks#44]
There is a Error "parse auth info failed" in FE when using the "SinkFunction<String> sink(StarRocksSinkOptions sinkOptions)"

> [BaseAction.getAuthorizationInfo():315] parse auth info failed, Authorization header null, url /api/xxxxxxxx fail to process url: /api/xxxxxxxxxxxxx
> com.starrocks.http.UnauthorizedException: Need auth information

But there is an Authorization in the header of PUT HTTP when I debug the process of Flink.

And I implement the code of a sample sink by using HttpClients with the header "Authorization", the stream load successes.

The version of "flink-connector-starrocks" is "1.1.10_flink-1.11"

**Comment by hffariel** [comment]
Paste your sink configurations here plz.

**Comment by zhaidongbo** [comment]
> Paste your sink configurations here plz.
```java
source
      .addSink(
        StarRocksSink.sink(
          StarRocksSinkOptions.builder()
            .withProperty("jdbc-url", "jdbc:mysql://XXXXXX:9030/test")
            .withProperty("load-url", "XXXXXX:8030")
            .withProperty("username", "root")
            .withProperty("password", "")
            .withProperty("table-name", "test_XXXXXX")
            .withProperty("database-name", "test")
            .withProperty("sink.properties.row_delimiter","\n")     
            .withProperty("sink.properties.column_separator","\t")   
            .withProperty("sink.buffer-flush.interval-ms","5000")
            .build()))
```

**Comment by hffariel** [comment]
Remove these lines:
```
.withProperty("sink.properties.row_delimiter","\n")     
.withProperty("sink.properties.column_separator","\t")
```

And add these for better compatibility:
```
.withProperty("sink.properties.format", "json")
.withProperty("sink.properties.strip_outer_array", "true")
```

**or** these for better performance:
```
.withProperty("sink.properties.row_delimiter","\\x01")     
.withProperty("sink.properties.column_separator","\\x02") 
```

**Comment by zhaidongbo** [comment]
> .withProperty("sink.properties.row_delimiter","\\x01")     
> .withProperty("sink.properties.column_separator","\\x02") 
It's OK, Great Job!
