### ISSUE TITLE
user flink-connector-starrocks Unable to insert starrocks with date filed

### ISSUE THREAD

**Issue by XW512** [StarRocks/flink-connector-starrocks#46]
When I use flink-connector-starrocks insert record to starrocks，When there is no date field, it can be inserted，
When I add a date field，The following error occurred：
com.starrocks.connector.flink.table.StarRocksDynamicSinkFunction [] - Unsupported row data invoked: [%s]
this is my code：

import java.util.Date;
public class RequestData {

    /**
     * 当前日期(用于starRocks的分区、分桶的处理)
     */
    private Date curDate;
}

SinkFunction<RequestData> starRocksSink = StarRocksSink.sink(TableSchema.builder()
                        .field("cur_date", DataTypes.DATE())
                        .field("id", DataTypes.STRING())
                        .build(),
        StarRocksSinkOptions.builder()
                        .withProperty("jdbc-url", "jdbc:mysql://XXX:9030,XXX:9030,XXX:9030")
                        .withProperty("load-url", "XXX:8030;XXX:8030;XXX:8030")
                        .withProperty("username", "root")
                        .withProperty("password", "root")
                        .withProperty("database-name", "test")
                        .withProperty("table-name", "logData_url")
                        .withProperty("sink.properties.format", "json")
                        .withProperty("sink.properties.strip_outer_array", "true")
                        .build(),
                (slots, requestLog) -> {
                    slots[0] = requestLog.getCurDate();
                    slots[1] = UUID.randomUUID().toString();
                }
 );

my Table structure：

CREATE TABLE test.logData_url
(
cur_date DATE,
id STRING
)
ENGINE=olap
COMMENT "log data"
DISTRIBUTED BY HASH(id) BUCKETS 32
PROPERTIES ("storage_type"="column");

I print out the inserted parameters:

{"id":"8bb09e5e110845f39sf00df668ef3e80","curDate":1643126400000}

I guess there is a problem with the format of curDate

How should I deal with this problem？thank you

**Comment by XW512** [comment]
the flink-connector-starrocks version is 1.1.14_flink-1.14_2.11

**Comment by hffariel** [comment]
Thanks for the feedback, and it will get fixed ASAP.

**Comment by XW512** [comment]
> Thanks for the feedback, and it will get fixed ASAP.

OK,It's fixed. Please let me know，thank you very much

**Comment by hffariel** [comment]
> > Thanks for the feedback, and it will get fixed ASAP.
> 
> OK,It's fixed. Please let me know，thank you very much

Has been fixed in the latest release `1.1.16`.
BTW, better to format the `Date` into a `String` before setting it into the slot.

**Comment by XW512** [comment]
> > > Thanks for the feedback, and it will get fixed ASAP.
> > 
> > 
> > OK,It's fixed. Please let me know，thank you very much
> 
> Has been fixed in the latest release `1.1.16`. BTW, better to format the `Date` into a `String` before setting it into the slot.

OK，I'll give it a try，thank you

**Comment by XW512** [comment]
> > > Thanks for the feedback, and it will get fixed ASAP.
> > 
> > 
> > OK,It's fixed. Please let me know，thank you very much
> 
> Has been fixed in the latest release `1.1.16`. BTW, better to format the `Date` into a `String` before setting it into the slot.

I have a question，This date field is mainly used for partitioning and bucket sorting. If it is converted to string storage, will it affect the processing of partitioning and bucket sorting，
Dynamic partition management link  https://docs.dorisdb.com/zh-cn/main/table_design/Data_distribution

**Comment by XW512** [comment]
> > > > Thanks for the feedback, and it will get fixed ASAP.
> > > 
> > > 
> > > OK,It's fixed. Please let me know，thank you very much
> > 
> > 
> > Has been fixed in the latest release `1.1.16`. BTW, better to format the `Date` into a `String` before setting it into the slot.
> 
> I have a question，This date field is mainly used for partitioning and bucket sorting. If it is converted to string storage, will it affect the processing of partitioning and bucket sorting， Dynamic partition management link https://docs.dorisdb.com/zh-cn/main/table_design/Data_distribution

I have updated the version and can adopt the treatment of partition and bucket，thank you

**Comment by hffariel** [comment]
What i'm saying is that if you wanna insert a `Date` into StarRocks, it has to be a `String` value like `2022-01-01`.

**Comment by hffariel** [comment]
I didn't mean that you have to replace `Date` with `String` in StarRocks.

**Comment by XW512** [comment]
> I didn't mean that you have to replace `Date` with `String` in StarRocks.

I understand，thank you very much

**Comment by XW512** [comment]
I found that using datetime for field in starrocks，If the set field relationship is in the code, it is found that the type verification of the field fails

this is my code

SinkFunction<RequestData> starRocksSink = StarRocksSink.sink(TableSchema.builder()
                        .field("cur_date", DataTypes.DATE())
                        .field("data_time", DataTypes.TIMESTAMP_WITH_TIME_ZONE())
                        .field("id", DataTypes.STRING())
                        .build(),
                StarRocksSinkOptions.builder()
                        .withProperty("jdbc-url", "jdbc:mysql://XXX:9030,XXX:9030,XXX:9030")
                        .withProperty("load-url", "XXX8030;XXX:8030;XXX:8030")
                        .withProperty("username", "root")
                        .withProperty("password", "root")
                        .withProperty("database-name", "test")
                        .withProperty("table-name", "logData_url")
                        .withProperty("sink.properties.format", "json")
                        .withProperty("sink.properties.strip_outer_array", "true")
                        .withProperty("sink.properties.column_separator", "\\x01")
                        .withProperty("sink.properties.row_delimiter", "\\x02")
                        .build(),
                (slots, requestLog) -> {
                    slots[0] = requestLog.getCurDate();
                    slots[1] = requestLog.getDataTime();
                    slots[2] = UUID.randomUUID().toString();
                }
        );

data_time filed is DATETIME

my Table structure：

CREATE TABLE test.logData_url
(
cur_date DATE,
data_time DATETIME,
id STRING
)
ENGINE=olap
COMMENT "log data"
DISTRIBUTED BY HASH(id) BUCKETS 32
PROPERTIES ("storage_type"="column");

The error is in this code

Fields name or type mismatch for:data_time at com.starrocks.connector.flink.manager.StarRocksSinkManager.validateTableStructure(StarRocksSinkManager.java:452)

 public StarRocksSinkManager(StarRocksSinkOptions sinkOptions, TableSchema flinkSchema) {
        this.sinkOptions = sinkOptions;
        StarRocksJdbcConnectionOptions jdbcOptions = new StarRocksJdbcConnectionOptions(sinkOptions.getJdbcUrl(), sinkOptions.getUsername(), sinkOptions.getPassword());
        this.jdbcConnProvider = new StarRocksJdbcConnectionProvider(jdbcOptions);
        this.starrocksQueryVisitor = new StarRocksQueryVisitor(jdbcConnProvider, sinkOptions.getDatabaseName(), sinkOptions.getTableName());
        // validate table structure
        typesMap = new HashMap<>();
        typesMap.put("bigint", Lists.newArrayList(LogicalTypeRoot.BIGINT, LogicalTypeRoot.INTEGER, LogicalTypeRoot.BINARY));
        typesMap.put("largeint", Lists.newArrayList(LogicalTypeRoot.DECIMAL, LogicalTypeRoot.BIGINT, LogicalTypeRoot.INTEGER, LogicalTypeRoot.BINARY));
        typesMap.put("char", Lists.newArrayList(LogicalTypeRoot.CHAR, LogicalTypeRoot.VARCHAR));
        typesMap.put("date", Lists.newArrayList(LogicalTypeRoot.DATE, LogicalTypeRoot.VARCHAR));
        typesMap.put("datetime", Lists.newArrayList(LogicalTypeRoot.TIMESTAMP_WITHOUT_TIME_ZONE, LogicalTypeRoot.VARCHAR));
        typesMap.put("decimal", Lists.newArrayList(LogicalTypeRoot.DECIMAL, LogicalTypeRoot.BIGINT, LogicalTypeRoot.INTEGER, LogicalTypeRoot.DOUBLE, LogicalTypeRoot.FLOAT));
        typesMap.put("double", Lists.newArrayList(LogicalTypeRoot.DOUBLE, LogicalTypeRoot.BIGINT, LogicalTypeRoot.INTEGER));
        typesMap.put("float", Lists.newArrayList(LogicalTypeRoot.FLOAT, LogicalTypeRoot.INTEGER));
        typesMap.put("int", Lists.newArrayList(LogicalTypeRoot.INTEGER, LogicalTypeRoot.BINARY));
        typesMap.put("tinyint", Lists.newArrayList(LogicalTypeRoot.TINYINT, LogicalTypeRoot.INTEGER, LogicalTypeRoot.BINARY, LogicalTypeRoot.BOOLEAN));
        typesMap.put("smallint", Lists.newArrayList(LogicalTypeRoot.SMALLINT, LogicalTypeRoot.INTEGER, LogicalTypeRoot.BINARY));
        typesMap.put("varchar", Lists.newArrayList(LogicalTypeRoot.VARCHAR, LogicalTypeRoot.ARRAY, LogicalTypeRoot.MAP, LogicalTypeRoot.ROW));
        typesMap.put("string", Lists.newArrayList(LogicalTypeRoot.CHAR, LogicalTypeRoot.VARCHAR, LogicalTypeRoot.ARRAY, LogicalTypeRoot.MAP, LogicalTypeRoot.ROW));
        validateTableStructure(flinkSchema);

the datetime validate is TIMESTAMP_WITHOUT_TIME_ZONE，but  flink DataTypes not TIMESTAMP_WITHOUT_TIME_ZONE，it only  TIMESTAMP_WITH_TIME_ZONE and TIMESTAMP_WITH_LOCAL_TIME_ZONE，How should I set the type of this field of data_time in code？

**Comment by hffariel** [comment]
DataTypes.TIMESTAMP will be OK. Cuz it is the same as the TIMESTAMP_WITHOUT_TIME_ZONE.

**Comment by XW512** [comment]
> DataTypes.TIMESTAMP will be OK. Cuz it is the same as the TIMESTAMP_WITHOUT_TIME_ZONE.

I modified the type and can insert data，thank you very much
