### ISSUE TITLE
can we change the  scope of dependency  relevant to the flink to provided?

### ISSUE THREAD

**Issue by baisui1981** [StarRocks/flink-connector-starrocks#6]
as you see , the scope of dependency  relevant to the flink is **compile**，

This will cause unnecessary trouble，when i introduce the dependency of flink-connector-starrocks to my pom.xml,
I must exclude the flink dependencis in advance .

so , can we change the  scope of dependency  relevant to the flink to provided?

**Comment by hffariel** [comment]
> as you see , the scope of dependency relevant to the flink is **compile**，
> 
> This will cause unnecessary trouble，when i introduce the dependency of flink-connector-starrocks to my pom.xml, I must exclude the flink dependencis in advance .
> 
> so , can we change the scope of dependency relevant to the flink to provided?
Sure, but the flink dependencies could be removed from the pom.xml directly i think, except for the `flink-table-planner-blink` and `flink-clients`(whose scope could be made to `provided` instead) as you said.

Happy to see any pull request  from you and thank you!
