### ISSUE TITLE
Using apache HttpClient lib to send stream load http request, can't support non-ascii column_separator like euro sign €

### ISSUE THREAD

**Issue by dannydjj** [StarRocks/flink-connector-starrocks#63]
When sink data to StarRocks, class StarRocksStreamLoadVisitor using HttpClient lib to send http request. 

column_separator should set  into the Http Header, but  HttpClient can't support non-ascii characters in http headers.

So, should use HttpURLConnection instead.

**Comment by hffariel** [comment]
Unfortunately, `non-ascii characters` are no longer suggested to be used in the header fields according to [this](https://www.rfc-editor.org/rfc/rfc7230#section-3.2.4).
And it has been a known issue of starrocks' `stream load api`.

Here may be the solution in the `upcoming starrocks' stream load api`:
1. Encode `non-ascii characters` before setting them into the header fields at the `client side`.
2. Try to decode the header fields before using them at the `fe or be side`.

We'll let you know ASAP once we work it out.
