### ISSUE TITLE
 flink sql table sink 写入SR表无效

### ISSUE THREAD

**Issue by wzq2468101** [StarRocks/flink-connector-starrocks#64]
1. 版本
   1. flink：1.13.3
   2. kafka：2.x
   3. SR：2.0.1
   4. 连接器：1.2.1-flink_1.13_2.12
   5. 采用精确一次语义写入，checkpoint为30秒触发一次。
 2.  异常描述 
       1. 精确一次
              1. 上游接收kafka数据，然后原生写入SR表，使用精确一次语义写入。flink sql任务模式为streaming。flink sql任务运行期间，无任何报错，所有checkpoint均成功，但是SR表并没有被写入数据。查看flink的TM角色日志，也没有任何报错。
              2. 如果停止flink任务写入，过2分钟之后，对应的表中即可查询到最新数据。
              3. 在任务运行期间，SR没有接收到任何stream load请求，任务停止之后，瞬间接收到非常多的stream load请求。
              4. 运行期间的所有数据都丢失了。
       2. 至少一次. 
              1. 将精确一次语义切换为至少一次，配置相关flush参数之后，写入正常，但是Compaction Cumulate明显增加，其他指标监控正常。
5. 其他
       1. 一共运行了16个相似的flink sql任务，均为上游接收kafka数据，下游写入SR表，有3个任务出现了这种情况，其中两个任务上游kafka数据量为35k/s，一个任务为1.5k/s。
       2. 一些奇怪日志
               Label [f95c2db9-6345-4b25-800c-f8a3e0755de7] has already been used.

**Comment by hffariel** [comment]
2.i : 1.12.1 版本 connector 的 exactly-once 导入问题已在各分支最新代码中修复，1.12.1 之前的版本不受影响。

2.ii: compaction增加跟导入频率相关，可以修改flush参数尽量保证每批次数据最大并降低导入频率。同时将checkpoint周期设为分钟级别。

3.2: 这个问题比较难解释
产生的直接原因是，某个label导入的状态有可能是未知的，但是be返回了fail（比如 failed to call frontend service），所以外部系统认为此次导入失败，再次使用相同label去做重试导入时，be其实还没有最终确定这个label的状态，所以返回了label already exists。此时connector会去check label state直至查到label的最终状态后，根据最终状态做对应的操作。因此最坏的情况就是任务会阻塞直到某个未知状态label最终timeout才可以继续。而stream load timeout默认时长为10分钟，如果想修改的话可以设置'sink.properties.timeout' = '30'来减少timeout等待时长。

根本原因为be不应该在未确定最终状态的情况下就返回fail给用户，这个会在后续sr的版本中修正。

**Comment by Goddywu** [comment]
@hffariel
