### ISSUE TITLE
Pom文件存在未设置的属性

### ISSUE THREAD

**Issue by hehuiyuan** [StarRocks/flink-connector-starrocks#71]
pom文件中file_encoding 属性没有定义
![image](https://user-images.githubusercontent.com/18002496/160360454-efe1772d-c9ee-4d89-9e8b-7b87bd8a7402.png)

**Comment by hffariel** [comment]
> pom文件中file_encoding 属性没有定义 ![image](https://user-images.githubusercontent.com/18002496/160360454-efe1772d-c9ee-4d89-9e8b-7b87bd8a7402.png)

PR is welcomed 😄

**Comment by hehuiyuan** [comment]
@hffariel okay😄
