### ISSUE TITLE
关于flink版本的支持

### ISSUE THREAD

**Issue by motto1314** [StarRocks/flink-connector-starrocks#77]
1、flink-1.11.0在v.1.2.1版本中不兼容，后续是否考虑兼容flink-1.11.0版本（需要有source的，目前flink-1.11分支没有source）
2、flink-1.15版本（即将发布）后期是否有考虑支持？

**Comment by hffariel** [comment]
1. flink-1.11.0 暂时还不考虑支持 source
2. flink-1.15正式版发布后就会进行支持，后续新版本都会持续支持。
